# Generated by Django 3.1.5 on 2021-01-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necessidades', '0001_initial'),
        ('atracoes', '0001_initial'),
        ('core', '0002_auto_20210120_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='atracao',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='necessidade_publica',
            field=models.ManyToManyField(to='necessidades.Necessidade_publica'),
        ),
    ]
