# Generated by Django 3.1.5 on 2021-01-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha1', models.CharField(max_length=150)),
                ('linha2', models.CharField(blank=True, max_length=150)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=80)),
                ('pais', models.CharField(max_length=80)),
                ('latitude', models.IntegerField(blank=True)),
                ('longitude', models.IntegerField(blank=True)),
            ],
        ),
    ]
