# Generated by Django 3.1.5 on 2021-01-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='latitude',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='longitude',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
